### PR TITLE
CAUSEWAY-3668: wip 

### PR DESCRIPTION
**Pull request by danhaywood**

### CODE REVIEW

**Comment by andi-huber** [comment]
There is a dependency clash with

- `jakarta.activation`
- `jakarta.activation-api`

Both provide the `javax.activation.DataSource`.

Excluding `jakarta.activation` from `spring-boot-starter-mail` in `causeway-core-runtimeservices` helps resolve that:

```xml
<dependency>
    <groupId>org.springframework.boot</groupId>
    <artifactId>spring-boot-starter-mail</artifactId>
    <exclusions>
        <exclusion>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-logging</artifactId>
        </exclusion>
        <exclusion>
           <groupId>com.sun.activation</groupId>
           <artifactId>jakarta.activation</artifactId>
        </exclusion>
    </exclusions>
</dependency>
```

**Comment by andi-huber** [comment]
`javax.activation.DataSource` is used to reference a mail attachment in our `EmailService` API. I just want to note that we have a similar `org.apache.causeway.commons.io.DataSource` that could be used instead (or in addition to not break backwards compatibility).

**Comment by danhaywood** [comment]
Hi @andi-huber  - that'd be great if you could bring this to completion - thanks!

**Comment by danhaywood** [comment]
(please feel free to rebase this branch as you see fit)

**Comment by andi-huber** [comment]
This branch/PR can be removed.

**Pull request closed without merging**
