### PR TITLE
CAUSEWAY-3741 - Enables hyphen in namespace

### PR DESCRIPTION
**Pull request by bkalbfus**

### CODE REVIEW

**Comment by bkalbfus** [comment]
I tested this by building causeway-app-simpleapp jdo-SNAPSHOT branch with the namespace modified to "simple-module".

**Comment by andi-huber** [comment]
Have you considered using `AsciiIdentifierService` SPI instead?

**Comment by danhaywood** [comment]
Hi @andi-huber  - I think that `AsciiIdentifierService` is only called to clean up the memberIds, but not the type names.

image

Given we already have this sanitization, and the code being changed is specific to the graphql viewer only, then I'm happy to have this change here.

**Comment by danhaywood** [comment]
@bkalbfus  - could you add an integration test and optionally a unit test to verify that this new code works correctly?

For example, you could take a copy of the CalculatorService and give it a namespace that requires sanitization?

**Comment by bkalbfus** [comment]
I would gladly!

**Comment by bkalbfus** [comment]
I updated my fork with the tests.  About to make a PR, but that would include commits from this PR.  And, I see my commit is showing on this PR after my comment, so is that enough for you to bring it in?  What is the preferred workflow?

**Comment by bkalbfus** [comment]
I checked what would happen to the tests if I changed the name of the test domain object, `org.apache.causeway.viewer.graphql.viewer.test.domain.i18n.I18nCalculator`, to `university.calc.I18nCälculator`.  A bunch of tests failed, so it looks like this sanitization is justified.  Or, more calls need to be put in to `AsciiIdentifierService`.

**Comment by andi-huber** [comment]
Thanks Brian.

Perhaps my preferred approach would have been to enhance the `AsciiIdentifierService`, in support of sanitizing namespaces. But then I'm also lazy and don't want to do the work. So happy with the current solution as well.

**Pull request merged**
